site:
  name: "Fuego Studio"
  base_url: ""

taxonomies:
  tags:
    path: "/tags/{term}"
    layout: "tag"
    index_path: "/tags"
    index_layout: "tag-index"

collections:
  tutorials:
    match: "docs/tutorials/**"
    sort_by: "order"
    layout: "listing"
    path: "/tutorials"
    page_size: 1
